 FROM nginx:latest
 COPY /dist/flight-management-angular /usr/share/nginx/html
 ENV NODE_ENV development



# Image creation command => 
            # syntax : "docker build -t imgName ." (at last space dot is also command)
			# example : "docker build -t flight-docker-image ."
			
# run image command =>
            # syntax : "docker run -p enterDockerContainerToRunOnWhichPort:enterYourAngularRunningPortNumber imgName"
			# example : "docker run -p 8084:8081 flight-docker-image"